from agents.case_classification import create_classification_agent
from agents.criminal_analysis import create_criminal_analysis_agent
from agents.web_search import create_web_search_agent
from agents.report_writer import create_report_writer_agent
from agents.court_decision import PutusanAgent